# Generated by Django 6.0.7 on 2026-07-11 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuwo_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('pic', models.URLField(max_length=500)),
                ('description', models.TextField()),
                ('source_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=300)),
                ('artist', models.CharField(blank=True, max_length=300)),
                ('album', models.CharField(blank=True, max_length=300)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('pic', models.URLField(blank=True, max_length=500)),
                ('lyrics', models.TextField()),
                ('source_url', models.URLField(max_length=500)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.singer')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.song')),
            ],
        ),
    ]
